package cards

var cards = map[string]Card{
	"the_fool": {
		Name:         "The Fool",
		Description:  "Freedom from conventions and norms. Something or someone unique and exceptional. Options kept open. Giving up control, spontaneity. Uncertainty, attention to the here and now. Going on a trip.",
		RDescription: "Difficulty in choosing and committing oneself to something stable. Restlessness. Lack of purpose. Getting lost. Foolish behavior. Eccentricity, lack of acceptance by the social environment. Difficulty in planning ahead.",
		Message:      "keep on the move",
		Type:         Major,
		Url:          "the_fool",
		Image:        "images/00.png",
	},
	"the_magician": {
		Name:         "The Magician",
		Description:  "The start of something. Beginner's luck. Having various tools and means at our disposal. Use of supernatural forces. Creating reality with mind power. Training and acquisition of practical skills. Improvisation. Display or show for other people.",
		RDescription: "Trickery, sleight of hand, cheating. Showing off, pretending. Lack of self-awareness about body, sexuality, or basic motives. Near miss due to inexperience or inaccuracy.",
		Message:      "create a new reality",
		Type:         Major,
		Url:          "the_magician",
		Image:        "images/01.png",
	},
	"the_high_priestess": {
		Name:         "The High Priestess",
		Description:  "Wisdom combining intellect and intuition. A spiritual mother. A woman hiding her strengths in a world of men. Modesty. Secrets, something hidden, mystery. Getting a hint of something which remains largely unknown. Impossible to give a definite answer now.",
		RDescription: "Need to hide our true nature behind the conventions of normal society. Conservative approach to sex and the body. Emotional blockage.",
		Message:      "know how to set boundaries",
		Type:         Major,
		Url:          "the_high_priestess",
		Image:        "images/02.png",
	},
	"the_empress": {
		Name:         "The Empress",
		Description:  "Abundance, growth, productivity. Natural or human touch within an artificial framework. Emotional intelligence. Protection and care. Motherhood. A powerful female figure. Strong feminine identity.",
		RDescription: "Impulsive behavior, someone difficult to reason with. Over-protectiveness, excessive involvement in the life of others. Problems with a strong mother figure.",
		Message:      "act from the guts",
		Type:         Major,
		Url:          "the_empress",
		Image:        "images/03.png",
	},
	"the_emperor": {
		Name:         "The Emperor",
		Description:  "Practical and material achievements. Matters relating to the workplace or source of income. Authority and control, a commanding position. A protective father figure, patron or sponsor. Assertiveness. Military affairs.",
		RDescription: "Belligerence, violence, trying to solve things by brute force. Dictatorship. Possibility of sexual abuse. Difficulty in coping with a dominant father figure. Denial and hiding of inner weaknesses.",
		Message:      "show leadership and responsibility",
		Type:         Major,
		Url:          "the_emperor",
		Image:        "images/04.png",
	},
	"the_pope": {
		Name:         "The Pope",
		Description:  "Teacher, instructor, or counselor. Education and knowledge, academic expertise. Organized religion, conventional medicine or psychology. Spiritual father. Consultation or treatment by a specialist. Marriage.",
		RDescription: "Excessive adhesion to conventions and outdated norms. Bureaucracy, an oppressive establishment. Hypocrisy, discrimination. Divorce.",
		Message:      "respect knowledge and education",
		Type:         Major,
		Url:          "the_pope",
		Image:        "images/05.png",
	},
	"the_lover": {
		Name:         "The Lover",
		Description:  "Love, amorous relationship. Emotional entanglement. Need to make a choice, or to disengage oneself from past influences. Inclinations of the heart correspond to the will of heaven. Small steps actually taken are the visible signs of inner desire.",
		RDescription: "Complex relationship between several people, e.g., a romantic triangle or a tension between mother and wife. Hesitation, quandary. Confusion as to one's own feeling and will.",
		Message:      "follow the path of the heart.",
		Type:         Major,
		Url:          "the_lover",
		Image:        "images/06.png",
	},
	"the_chariot": {
		Name:         "The Chariot",
		Description:  "Victory or an achievement putting the querent in a strong and protected position. Ambition, energy, motivation to move forward. Public honor. Power and high status.",
		RDescription: "Inner weakness hidden behind external show-off. Arrogance, vanity. Over-protectiveness, emotional closure. Confusion about one's goals. Losing the simple touch with people and reality.",
		Message:      "dare and win",
		Type:         Major,
		Url:          "the_chariot",
		Image:        "images/07.png",
	},
	"justice": {
		Name:         "Justice",
		Description:  "Law and order, legal and court issues. A fair and balanced judgment. A developed conscience. Rationality, reasoning by clear rules and common norms. Touch of grace and humanity beyond the objective considerations.",
		RDescription: "Petty accountability, a critical and judgmental attitude, guilt feelings. Repressive control of self and of others. Negative ideas blocking change and advance.",
		Message:      "act with reason and by the accepted norms",
		Type:         Major,
		Url:          "justice",
		Image:        "images/08.png",
	},
	"the_hermit": {
		Name:         "The Hermit",
		Description:  "A quest for truth or for spiritual understanding. Concentrating on a clear purpose. Caution, careful examination. Self-privation for the sake of a meaningful cause. Loyalty to principles, strong faith.",
		RDescription: "A closed and reclusive attitude. Isolation, loneliness. Fixed ideas. Excessive caution and suspicion, a critical approach looking for defects. Hidden and denied desires.",
		Message:      "look for the essence of things",
		Type:         Major,
		Url:          "the_hermit",
		Image:        "images/09.png",
	},
	"the_wheel_of_fortune": {
		Name:         "Wheel of Fortune",
		Description:  "Change in circumstances and position. A rise after a fall. Gambling, putting faith in capricious luck. Life cycles, closure of circles. Adapting to the routine of everyday life. A hint to previous incarnations.",
		RDescription: "A decline after a period of rising. Danger lurks at the summit. Moving in a closed circle. Capricious mood changes. Feeling powerless to affect one's situation.",
		Message:      "accept life's ups and downs",
		Type:         Major,
		Url:          "the_wheel_of_fortune",
		Image:        "images/10.png",
	},
	"strength": {
		Name:         "Strength",
		Description:  "Power and courage to face challenges. Controlled expression of creative urges, drives and desires. Mobilization of inner resources towards a common goal. Taking risks.",
		RDescription: "The need to keep things under control leads to constant tensions. A risk of losing one's grip. Internal conflicts and unrealistic assessment of one's own forces may lead to failure.",
		Message:      "take control of yourself",
		Type:         Major,
		Url:          "strength",
		Image:        "images/11.png",
	},
	"the_hanged_man": {
		Name:         "The Hanged Man",
		Description:  "Seeing things from a unique point of view. Enduring difficulties for a worthy cause. A period of deep self examination. Passivity, acceptance of reality even if it is the opposite of what one expects.",
		RDescription: "Isolation. Emotional stance of a victim. Inability to act. Denying one's own unique qualities, striving to be “normal” at all costs. Living in one's private and imaginary reality.",
		Message:      "look at things from the opposite perspective",
		Type:         Major,
		Url:          "the_hanged_man",
		Image:        "images/12.png",
	},
	"13": {
		Name:         "The Death",
		Description:  "The end of something whose time has come. Cutting off past influences or attachment to dominant figures. Giving up the superfluous and keeping only the essential. Disintegration of the old makes room for the new.",
		RDescription: "Difficulty in coping with loss or change. Temporary difficulties, a trying challenge. Disintegration. Realisation of a painful truth. Does not predict future death, but may reflect anxiety about dying or mourning over a loss which has already happened.",
		Message:      "give up what is over",
		Type:         Major,
		Url:          "13",
		Image:        "images/13.png",
	},
	"temperance": {
		Name:         "Temperance",
		Description:  "Reconciliation, compromise, relaxation of tensions. Integration of opposites. Ability to do the seemingly impossible. A slow process of distillation and improvement. Patience, perseverance. Self-improvement.",
		RDescription: "Going back and forth without making real progress. Losing patience with a lengthy process. Emotional preoccupation with oneself, pushing away others who might come to help.",
		Message:      "find the golden mean",
		Type:         Major,
		Url:          "temperance",
		Image:        "images/14.png",
	},
	"the_devil": {
		Name:         "The Devil",
		Description:  "A burst of creativity. Paradoxes and contradictions. Irony and mocking of common norms. Acting from desires, passions and impulses. Moving on from a past family trauma.",
		RDescription: "Temptation, attraction to the dark and forbidden. Exploitation, egotism, domination. Compulsive self-gratification. Senseless behavior has its price. Difficulty in detaching oneself from an unhealthy bond.",
		Message:      "express passion and desire.",
		Type:         Major,
		Url:          "the_devil",
		Image:        "images/15.png",
	},
	"the_tower": {
		Name:         "The Tower",
		Description:  "Breaking up of solid structures. Getting free from confinement. Sudden breakthrough after long preparations. Sparkling sexual encounter. Success lies in simplicity and modesty.",
		RDescription: "Shock, collapse of projects or trusted structures. A fall from an apparently solid and secure position. Chaos, confusion, difficulty in understanding what is going on. Vanity and pride lead to failure.",
		Message:      "return to the solid ground of reality",
		Type:         Major,
		Url:          "the_tower",
		Image:        "images/16.png",
	},
	"the_star": {
		Name:         "The Star",
		Description:  "Openness, simplicity, return to nature. Purity, honesty. Showing yourself “as you are,” accepting one's body and desires. Generosity. Luck from heaven. Intuitive feeling of guidance or energy coming from a higher plane.",
		RDescription: "Naive optimism and wishful-thinking. Exposing oneself to danger or abuse. Difficulty in setting proper boundaries. Squandering, wastefulness.",
		Message:      "flow from a pure source",
		Type:         Major,
		Url:          "the_star",
		Image:        "images/17.png",
	},
	"the_moon": {
		Name:         "The Moon",
		Description:  "Deep emotions, perhaps related to a mother or feminine figure. A different experience of reality. Longing for the unreachable. Finding one's hidden strengths. Occupation with the remote past. A hidden treasure.",
		RDescription: "Vague and disturbing feelings. Emotional difficulties, a period of depression. Danger lurking under the surface. Retreat, the road ahead is hard to find.",
		Message:      "don't be afraid to go deep down",
		Type:         Major,
		Url:          "the_moon",
		Image:        "images/18.png",
	},
	"the_sun": {
		Name:         "The Sun",
		Description:  "Light and warmth, abundance, blessings. Pleasant feeling, emotional or physical healing. Partnership, trust, sharing, brotherhood. Human touch. An ideal father figure. Matters relating to children. Setting limits in a moderate and non-oppressive way.",
		RDescription: "Living in a limited space, difficulty to face reality “in the open.” Immaturity, dependence on others. Someone or something too intense and energetic to feel comfortable with. An absent father.",
		Message:      "find suitable partners",
		Type:         Major,
		Url:          "the_sun",
		Image:        "images/19.png",
	},
	"judgement": {
		Name:         "Judgement",
		Description:  "Revelation, enlightenment, a new understanding. A turning point in a therapy process. Healing of a family relationship. Disclosure, secrets revealed, publicity. Birth of a baby or of a new thing.",
		RDescription: "Revelation of something that should have been kept hidden. Lack of privacy. Unpleasant realization. Problems related to child-parent relations. Too much noise and drama.",
		Message:      "awaken to spiritual reality",
		Type:         Major,
		Url:          "judgement",
		Image:        "images/20.png",
	},
	"the_world": {
		Name:         "The World",
		Description:  "Completion of a process. Balanced activity and achievements in various domains. Contact with far places. Harmony and correspondence between different planes. Pregnancy, something new is about to be born. The Dance of Life.",
		RDescription: "Life in a bubble, difficulty in sharing your world with others. Disconnection of inner feelings from external life. Preoccupation with oneself, idealized self-image, inability to move forward.",
		Message:      "everything is perfect as it is",
		Type:         Major,
		Url:          "the_world",
		Image:        "images/21.png",
	},
	"ace_of_clubs": {
		Name:         "Ace of Clubs",
		Description:  "Creative momentum. Active sexuality. Strong impulses, energy and drive. Life force. Beginning of growth. Dispersing one's efforts in different directions.",
		RDescription: "Lack of energy, restriction, repressed sexuality, a creative block.",
		Message:      "",
		Type:         Minor,
		Url:          "ace_of_clubs",
		Image:        "images/22.png",
	},
	"two_of_clubs": {
		Name:         "Two of Clubs",
		Description:  "Crossroads. Several options or ways to choose from. Every course offers benefits. A brief encounter with someone going his own way. Blocking an opponent's line of advance.",
		RDescription: "(similar to upright) Crossroads. Several options or ways to choose from. Every course offers benefits. A brief encounter with someone going his own way. Blocking an opponent's line of advance.",
		Message:      "",
		Type:         Minor,
		Url:          "two_of_clubs",
		Image:        "images/23.png",
	},
	"three_of_clubs": {
		Name:         "Three of Clubs",
		Description:  "Direction. Moving forward after a moment of hesitation. Finding a middle path between two courses of action. Gaining an advantage by keeping neutrality between two conflicting sides.",
		RDescription: "(similar to upright) Direction. Moving forward after a moment of hesitation. Finding a middle path between two courses of action. Gaining an advantage by keeping neutrality between two conflicting sides.",
		Message:      "",
		Type:         Minor,
		Url:          "three_of_clubs",
		Image:        "images/24.png",
	},
	"four_of_clubs": {
		Name:         "Four of Clubs",
		Description:  "Stalemate. A temporary stop in order to prepare for future advancement. Tensions at present, but good prospects in the long run. Making a move now is in nobody's interest.",
		RDescription: "(similar to upright) Stalemate. A temporary stop in order to prepare for future advancement. Tensions at present, but good prospects in the long run. Making a move now is in nobody's interest.",
		Message:      "",
		Type:         Minor,
		Url:          "four_of_clubs",
		Image:        "images/25.png",
	},
	"five_of_clubs": {
		Name:         "Five of Clubs",
		Description:  "Overcoming. Getting over a weak opposition. Breakdown of an equilibrium. Focusing on the main objective. An initiative to make a winning move.",
		RDescription: "With the covering part of the central wand below – walking into a complex situation, losing one's edge.",
		Message:      "",
		Type:         Minor,
		Url:          "five_of_clubs",
		Image:        "images/26.png",
	},
	"six_of_clubs": {
		Name:         "Six of Clubs",
		Description:  "Collaboration. A strong alliance between two parties with different goals but common present interests. A taste for luxury made possible by favorable conditions.",
		RDescription: "With the decorated flower at the bottom – excessive pursuit of luxury. Need to break up an alliance of opponents.",
		Message:      "",
		Type:         Minor,
		Url:          "six_of_clubs",
		Image:        "images/27.png",
	},
	"seven_of_clubs": {
		Name:         "Seven of Clubs",
		Description:  "Struggle. Someone putting up a fight against many opponents. Obstinacy, endurance, keeping one's position in a conflict situation. A difficult combat with an uncertain outcome.",
		RDescription: "(similar to upright) Struggle. Someone putting up a fight against many opponents. Obstinacy, endurance, keeping one's position in a conflict situation. A difficult combat with an uncertain outcome.",
		Message:      "",
		Type:         Minor,
		Url:          "seven_of_clubs",
		Image:        "images/28.png",
	},
	"eight_of_clubs": {
		Name:         "Eight of Clubs",
		Description:  "Regulation. It is possible to advance only by following the rules. Occupation with short-term goals while losing the long-term perspective. A roadblock.",
		RDescription: "(similar to upright) Regulation. It is possible to advance only by following the rules. Occupation with short-term goals while losing the long-term perspective. A roadblock.",
		Message:      "",
		Type:         Minor,
		Url:          "eight_of_clubs",
		Image:        "images/29.png",
	},
	"nine_of_clubs": {
		Name:         "Nine of Clubs",
		Description:  "Interruption. Difficulties and oppositions too hard to overcome. Giving up one's projects to avoid conflict. Starting anew after a challenging period.",
		RDescription: "(similar to upright) Interruption. Difficulties and oppositions too hard to overcome. Giving up one's projects to avoid conflict. Starting anew after a challenging period.",
		Message:      "",
		Type:         Minor,
		Url:          "nine_of_clubs",
		Image:        "images/30.png",
	},
	"ten_of_clubs": {
		Name:         "Ten of Clubs",
		Description:  "Loyalty. A partnership or an alliance endures hardships and succeeds in getting over them. Pure intentions and perseverance lead to success. Honoring one's principles in spite of difficulties.",
		RDescription: "(similar to upright) Loyalty. A partnership or an alliance endures hardships and succeeds in getting over them. Pure intentions and perseverance lead to success. Honoring one's principles in spite of difficulties.",
		Message:      "",
		Type:         Minor,
		Url:          "ten_of_clubs",
		Image:        "images/31.png",
	},
	"page_of_clubs": {
		Name:         "Page of Clubs",
		Description:  "A creative potential which still needs processing. Keeping a safe distance from events and waiting for the right moment.",
		RDescription: "A task too heavy for the querent's strength. Difficulty in controlling desires and urges. Immature approach to sexuality.",
		Message:      "",
		Type:         Minor,
		Url:          "page_of_clubs",
		Image:        "images/32.png",
	},
	"knight_of_clubs": {
		Name:         "Knight of Clubs",
		Description:  "A change of direction, following one's urges and passions. A temporary stop, but there is still energy and a desire to advance.",
		RDescription: "Preoccupation with the satisfaction of one's own desires. Problem in defining long-term goals. Submitting to temptation.",
		Message:      "",
		Type:         Minor,
		Url:          "knight_of_clubs",
		Image:        "images/33.png",
	},
	"queen_of_clubs": {
		Name:         "Queen of Clubs",
		Description:  "A feminine figure with a strong personality. Things connected with food and eating. Speaking softly while holding a big stick. A secure, well-defended position.",
		RDescription: "Intimidation, menace. Using sexuality as a means of control. Problems with a strong mother figure. Fear of feminine power.",
		Message:      "",
		Type:         Minor,
		Url:          "queen_of_clubs",
		Image:        "images/34.png",
	},
	"king_of_clubs": {
		Name:         "King of Clubs",
		Description:  "A mature attitude to urges and desires. Controlled creativity. Prodding oneself to make a move forward. Investing present assets in future projects.",
		RDescription: "Plans to move forward are frustrated by self-defeating acts. Hesitation, conflicts, tendency to make things too heavy and complex.",
		Message:      "",
		Type:         Minor,
		Url:          "king_of_clubs",
		Image:        "images/35.png",
	},
	"ace_of_cups": {
		Name:         "Ace of Cups",
		Description:  "The beginning of a love relationship. Expression of warm feelings. Romantic longing for something extraordinary. Emotional and spiritual growth.",
		RDescription: "Emotional dryness, feeling oneself empty. Avoidance of intimacy, negative feelings, heartbreak.",
		Message:      "",
		Type:         Minor,
		Url:          "ace_of_cups",
		Image:        "images/36.png",
	},
	"two_of_cups": {
		Name:         "Two of Cups",
		Description:  "Partnership. A romantic relationship or a close personal alliance. Interpersonal dynamics based on social norms. Passion in a love relationship, which may turn against itself.",
		RDescription: "A crisis in a couple relationship, disappointment with someone close to you.",
		Message:      "",
		Type:         Minor,
		Url:          "two_of_cups",
		Image:        "images/37.png",
	},
	"three_of_cups": {
		Name:         "Three of Cups",
		Description:  "Birth. Something new brings joy and happiness. Caring for a child. Issues of child-parent relations. A common project motivated by feelings and not only by interests.",
		RDescription: "Problems in relations with one's parents, or with one's child. A strong alliance of two persons leaves a third one outside.",
		Message:      "",
		Type:         Minor,
		Url:          "three_of_cups",
		Image:        "images/38.png",
	},
	"four_of_cups": {
		Name:         "Four of Cups",
		Description:  "Family. A collective of people (family, community etc.) with a history and a sense of belonging. Commitment to a group, at the price of giving up personal interests.",
		RDescription: "Problems and discord in the family or in a long-lasting community. A fixed social structure which doesn't allow for adaptation or flexibility.",
		Message:      "",
		Type:         Minor,
		Url:          "four_of_cups",
		Image:        "images/39.png",
	},
	"five_of_cups": {
		Name:         "Five of Cups",
		Description:  "Links. Popularity, relations with many people. Becoming the center of attention in a group. Relying on connections with other people to advance oneself or to overcome difficulties.",
		RDescription: "Excessive preoccupation with social activity. Losing oneself in multiple superficial connections. Cultivating virtual instead of real contacts.",
		Message:      "",
		Type:         Minor,
		Url:          "five_of_cups",
		Image:        "images/40.png",
	},
	"six_of_cups": {
		Name:         "Six of Cups",
		Description:  "Continuity. A long-term relationship. Repetition between different generations in the family. A stable personal alliance.",
		RDescription: "Monotony, tedious repetition. Falling time and again into the same emotional traps.",
		Message:      "",
		Type:         Minor,
		Url:          "six_of_cups",
		Image:        "images/41.png",
	},
	"seven_of_cups": {
		Name:         "Seven of Cups",
		Description:  "Individuality. A single person finding his place in a group. Contact with people in high positions. Exceptional qualities are appreciated.",
		RDescription: "Problems of integration in a group or an organization. Being part of a collective, but feeling isolated and estranged.",
		Message:      "",
		Type:         Minor,
		Url:          "seven_of_cups",
		Image:        "images/42.png",
	},
	"eight_of_cups": {
		Name:         "Eight of Cups",
		Description:  "Involvement. Developing personal relationships within a group. A favorable human-relations environment. A feast or a family event.",
		RDescription: "Interference of the environment in a couple's relationships. Pressures from one's family in romantic or personal matters.",
		Message:      "",
		Type:         Minor,
		Url:          "eight_of_cups",
		Image:        "images/43.png",
	},
	"nine_of_cups": {
		Name:         "Nine of Cups",
		Description:  "Collectivity. A group or organization working harmoniously with everyone finding his proper place. Accepting one's role in a social environment. Happiness, wishes coming true.",
		RDescription: "A confusing social situation, difficulty in situating oneself within a complex environment.",
		Message:      "",
		Type:         Minor,
		Url:          "nine_of_cups",
		Image:        "images/44.png",
	},
	"ten_of_cups": {
		Name:         "Ten of Cups",
		Description:  "Leadership. A person with special qualities receives appreciation and high status. Assuming responsibility for others. Maintaining a superior position.",
		RDescription: "A fallen leader, loss of popularity. Disappointment because of ingratitude by people one has helped.",
		Message:      "",
		Type:         Minor,
		Url:          "ten_of_cups",
		Image:        "images/45.png",
	},
	"page_of_cups": {
		Name:         "Page of Cups",
		Description:  "First and unsure steps in a romantic endeavor. Shyness. Sincere intentions. Trying to figure out one's feelings.",
		RDescription: "Over-absorption in one's personal feelings, losing contact with others. Sloppiness in practical affairs.",
		Message:      "",
		Type:         Minor,
		Url:          "page_of_cups",
		Image:        "images/46.png",
	},
	"knight_of_cups": {
		Name:         "Knight of Cups",
		Description:  "A romantic gesture, offering one's heart, courting. Openness, sincerity, a simple heart. A potential lover may appear.",
		RDescription: "Superficial and unstable feelings. An over-optimistic but unrealistic attitude. An overt display of shallow or insincere feelings. ",
		Message:      "",
		Type:         Minor,
		Url:          "knight_of_cups",
		Image:        "images/47.png",
	},
	"queen_of_cups": {
		Name:         "Queen of Cups",
		Description:  "A rich inner world which is kept hidden. Guarding one's privacy or valuable assets. Strong feelings held under control.",
		RDescription: "Closure, defensiveness. Distrust of others due to negative past experiences. Hiding one's emotions under guise of rational criticism.",
		Message:      "",
		Type:         Minor,
		Url:          "queen_of_cups",
		Image:        "images/48.png",
	},
	"king_of_cups": {
		Name:         "King of Cups",
		Description:  "Emotional maturity, optimism, ability to overcome past injuries and look ahead. Openness to new things, but with prudence and caution. Closing one's ear to voices from the past.",
		RDescription: "Difficulty in overcoming an emotional blow. A pessimistic outlook caused by negative past experiences. ",
		Message:      "",
		Type:         Minor,
		Url:          "king_of_cups",
		Image:        "images/49.png",
	},
	"ace_of_swords": {
		Name:         "Ace of Swords",
		Description:  "A planned initiative. Rational and logical thinking, sharpness of mind. A conclusive decision. Readiness to fight. Ambition, competitiveness. A victory with stable achievements.",
		RDescription: "Negative and unproductive thoughts. Misconceptions, delusions. Self-defeat. Injury.",
		Message:      "",
		Type:         Minor,
		Url:          "ace_of_swords",
		Image:        "images/50.png",
	},
	"two_of_swords": {
		Name:         "Two of Swords",
		Description:  "Boundaries. Limits that protect and define something which is in development. Making full use of the present situation. Preparations for future advancement. A clear view encompassing the overall situation.",
		RDescription: "(similar to upright) Boundaries. Limits that protect and define something which is in development. Making full use of the present situation. Preparations for future advancement. A clear view encompassing the overall situation.",
		Message:      "",
		Type:         Minor,
		Url:          "two_of_swords",
		Image:        "images/51.png",
	},
	"three_of_swords": {
		Name:         "Three of Swords",
		Description:  "Victory. Overcoming a weak opposition. Cutting through a quandary and going forward in a clear direction. A third party intervenes and wins over two weakened opponents.",
		RDescription: "A failure, defeat from a weaker opponent. An unsuccessful attempt to make a decisive move.",
		Message:      "",
		Type:         Minor,
		Url:          "three_of_swords",
		Image:        "images/52.png",
	},
	"four_of_swords": {
		Name:         "Four of Swords",
		Description:  "Restriction. A limited space for development and maneuver. Trying to push against constraints. Potentials to grow once the present limitations become less solid.",
		RDescription: "Confinement and blocking, lack of motivation or energy to break out of a limited situation.",
		Message:      "",
		Type:         Minor,
		Url:          "four_of_swords",
		Image:        "images/53.png",
	},
	"five_of_swords": {
		Name:         "Five of Swords",
		Description:  "Breakthrough. A forward thrust overcoming the existing limits. Keeping up spirits in a tight situation. Doing things one's own way.",
		RDescription: "A failed initiative to change the situation. Stubbornness leading nowhere. Oppressing factors cannot be removed now.",
		Message:      "",
		Type:         Minor,
		Url:          "five_of_swords",
		Image:        "images/54.png",
	},
	"six_of_swords": {
		Name:         "Six of Swords",
		Description:  "Adaptation. Accepting limitations and adapting oneself to them. Respecting the present order. Compromising in order to make the best of the existing situation.",
		RDescription: "Resignation, surrender, giving up the ambition to change things for the better. Lack of fighting spirit.",
		Message:      "",
		Type:         Minor,
		Url:          "six_of_swords",
		Image:        "images/55.png",
	},
	"seven_of_swords": {
		Name:         "Seven of Swords",
		Description:  "Sharpness. A focused and determined attitude. Concentrating on a clear goal and doing what it takes to reach it. Winning a fight with the odds evenly balanced.",
		RDescription: "A narrow and over-concentrated vision. Investing one's efforts and resources in a lost cause.",
		Message:      "",
		Type:         Minor,
		Url:          "seven_of_swords",
		Image:        "images/56.png",
	},
	"eight_of_swords": {
		Name:         "Eight of Swords",
		Description:  "Defenses. Putting up shields and blocks. Psychological defense mechanisms. A need to be in total control. A well-guarded treasure. Entering another's domain with permission.",
		RDescription: "(similar to upright) Defenses. Putting up shields and blocks. Psychological defense mechanisms. A need to be in total control. A well-guarded treasure. Entering another's domain with permission.",
		Message:      "",
		Type:         Minor,
		Url:          "eight_of_swords",
		Image:        "images/57.png",
	},
	"nine_of_swords": {
		Name:         "Nine of Swords",
		Description:  "Courage. Winning a fight against a superior force. Pure intentions. Putting imperfect means to good use.",
		RDescription: "Losing against a stronger opponent. Sloppiness, imperfect preparations for a challenge.",
		Message:      "",
		Type:         Minor,
		Url:          "nine_of_swords",
		Image:        "images/58.png",
	},
	"ten_of_swords": {
		Name:         "Ten of Swords",
		Description:  "Exhaustion. A complex situation with many conflicting interests. A long battle without a clear outcome. Need to find an ally who will attack the problem from a different direction.",
		RDescription: "Immobility. Impossible to move now. Feeling attacked from different sides. A painful and humiliating defeat.",
		Message:      "",
		Type:         Minor,
		Url:          "ten_of_swords",
		Image:        "images/59.png",
	},
	"page_of_swords": {
		Name:         "Page of Swords",
		Description:  "Preparation for a future challenge. Looking for a compromise between reason and strong desires. Hesitating to use one's power.",
		RDescription: "Confusion, negative and inhibiting thoughts, self-defeat. Sloppy use of one's own tools may cause damage.",
		Message:      "",
		Type:         Minor,
		Url:          "page_of_swords",
		Image:        "images/60.png",
	},
	"knight_of_swords": {
		Name:         "Knight of Swords",
		Description:  "Energy and resources to advance, still looking for the right direction. Hovering above practical constraints. Determination and perseverance.",
		RDescription: "Trying to force one's misguided views, insisting on a wrong direction. Losing touch with the ground.",
		Message:      "",
		Type:         Minor,
		Url:          "knight_of_swords",
		Image:        "images/61.png",
	},
	"queen_of_swords": {
		Name:         "Queen of Swords",
		Description:  "A secure and protected position. Defending one's territory. Preparation of something that shouldn't be exposed yet.",
		RDescription: "Defensiveness and rigidity. Suspicion and fixed ideas block advancement and preclude new connections.",
		Message:      "",
		Type:         Minor,
		Url:          "queen_of_swords",
		Image:        "images/62.png",
	},
	"king_of_swords": {
		Name:         "King of Swords",
		Description:  "A determination to break from the past, a strong will. Feeling equipped to deal with uncertainty. Wisdom and intellectual maturity.",
		RDescription: "A divided heart, a need to cut off from something to which one is still attached. Over-calculating in a vain attempt to overcome uncertainty.",
		Message:      "",
		Type:         Minor,
		Url:          "king_of_swords",
		Image:        "images/63.png",
	},
	"ace_of_coins": {
		Name:         "Ace of Coins",
		Description:  "A good start in material things. Financial and physical stability. A practical perspective. A significant sum of money. Utilitarian approach. Greed. Something basic and unsophisticated.",
		RDescription: "(similar to upright) A good start in material things. Financial and physical stability. A practical perspective. A significant sum of money. Utilitarian approach. Greed. Something basic and unsophisticated.",
		Message:      "",
		Type:         Minor,
		Url:          "ace_of_coins",
		Image:        "images/64.png",
	},
	"two_of_coins": {
		Name:         "Two of Coins",
		Description:  "Duality. Two options or two elements. Collaborating while keeping distance. A winding road, advancing in complex ways. Recognition and acknowledgment.",
		RDescription: "(similar to upright) Duality. Two options or two elements. Collaborating while keeping distance. A winding road, advancing in complex ways. Recognition and acknowledgment.",
		Message:      "",
		Type:         Minor,
		Url:          "two_of_coins",
		Image:        "images/65.png",
	},
	"three_of_coins": {
		Name:         "Three of Coins",
		Description:  "Product. A partnership or an alliance bears fruit. First results of a project. Good prospects.",
		RDescription: "Disappointment, a partnership or a project does not bear the expected fruits.",
		Message:      "",
		Type:         Minor,
		Url:          "three_of_coins",
		Image:        "images/66.png",
	},
	"four_of_coins": {
		Name:         "Four of Coins",
		Description:  "Stability. Solid material assets. Tradition, reputation and honor. Time-tested reliability. Established social institutions.",
		RDescription: "Conservatism, clinging to old and outdated patterns.",
		Message:      "",
		Type:         Minor,
		Url:          "four_of_coins",
		Image:        "images/67.png",
	},
	"five_of_coins": {
		Name:         "Five of Coins",
		Description:  "Disruption. Something new appears and destabilizes existing structures. A new element gets attention, but also awakens resistance.",
		RDescription: "(similar to upright) Disruption. Something new appears and destabilizes existing structures. A new element gets attention, but also awakens resistance.",
		Message:      "",
		Type:         Minor,
		Url:          "five_of_coins",
		Image:        "images/68.png",
	},
	"six_of_coins": {
		Name:         "Six of Coins",
		Description:  "Expansion. Abundance of resources and possible ways to advance. A positive outlook, success. A good balance between stability and movement.",
		RDescription: "(similar to upright) Expansion. Abundance of resources and possible ways to advance. A positive outlook, success. A good balance between stability and movement.",
		Message:      "",
		Type:         Minor,
		Url:          "six_of_coins",
		Image:        "images/69.png",
	},
	"seven_of_coins": {
		Name:         "Seven of Coins",
		Description:  "Acceptance. Something new is well received. Help and protection. Integrating into a system without losing one's individuality.",
		RDescription: "Lack of independence, need to rely on help and acceptance from others.",
		Message:      "",
		Type:         Minor,
		Url:          "seven_of_coins",
		Image:        "images/70.png",
	},
	"eight_of_coins": {
		Name:         "Eight of Coins",
		Description:  "Uniformity. A mechanical structure. Practical considerations prove efficient, but lack a human touch. Routine work. A slow and patient advance.",
		RDescription: "(similar to upright) Uniformity. A mechanical structure. Practical considerations prove efficient, but lack a human touch. Routine work. A slow and patient advance.",
		Message:      "",
		Type:         Minor,
		Url:          "eight_of_coins",
		Image:        "images/71.png",
	},
	"nine_of_coins": {
		Name:         "Nine of Coins",
		Description:  "Motivation. Carving a niche for oneself in an existing system. Ambition. Endurance and independent thinking bear long-term fruits.",
		RDescription: "(similar to upright) Motivation. Carving a niche for oneself in an existing system. Ambition. Endurance and independent thinking bear long-term fruits.",
		Message:      "",
		Type:         Minor,
		Url:          "nine_of_coins",
		Image:        "images/72.png",
	},
	"ten_of_coins": {
		Name:         "Ten of Coins",
		Description:  "Abundance. Intensive activity in practical affairs. Material success and achievements. Some may be getting more than others.",
		RDescription: "(similar to upright) Abundance. Intensive activity in practical affairs. Material success and achievements. Some may be getting more than others.",
		Message:      "",
		Type:         Minor,
		Url:          "ten_of_coins",
		Image:        "images/73.png",
	},
	"page_of_coins": {
		Name:         "Page of Coins",
		Description:  "A practical endeavor. Untapped potentials are within reach. Tangible success at the beginning. A solid material base for further advancement.",
		RDescription: "Hesitation, lack of clear purpose. Thinking in terms of past achievements misses present opportunities.",
		Message:      "",
		Type:         Minor,
		Url:          "page_of_coins",
		Image:        "images/74.png",
	},
	"knight_of_coins": {
		Name:         "Knight of Coins",
		Description:  "Advancement in a practical direction. A productive expression of creativity. A clear goal in sight.",
		RDescription: "Constant pursuit of money, without reaching material stability. Passions and desires may interfere with practical plans.",
		Message:      "",
		Type:         Minor,
		Url:          "knight_of_coins",
		Image:        "images/75.png",
	},
	"queen_of_coins": {
		Name:         "Queen of Coins",
		Description:  "Tangible assets, material and personal stability, a sober and realistic vision. Looking at things from a practical and pragmatic perspective.",
		RDescription: "Conservatism, resistance to change, aiming only to preserve the existing assets. Looking at things only from the material perspective.",
		Message:      "",
		Type:         Minor,
		Url:          "queen_of_coins",
		Image:        "images/76.png",
	},
	"king_of_coins": {
		Name:         "King of Coins",
		Description:  "Confidence and security, a cautious but optimistic vision. Looking for new achievements while holding existing assets secure.",
		RDescription: "Dissatisfaction with what one already has. Disregard of the good things in the present situation. A limited outlook.",
		Message:      "",
		Type:         Minor,
		Url:          "king_of_coins",
		Image:        "images/77.png",
	},
}
